apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - port: {{ .Values.elasticsearch.port }}
      targetPort: {{ .Values.elasticsearch.port }}
