apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - port: {{ .Values.kafka.port }}
      targetPort: {{ .Values.kafka.port }}
