spring:
  application:
    name: gateway-service
  profiles:
    active: local

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway  # health는 k8s 프로브에서 사용
  endpoint:
    gateway:
      enabled: true
