apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE user_db;
    CREATE DATABASE report_db;
    CREATE DATABASE search_db;
    \c search_db
    CREATE EXTENSION IF NOT EXISTS vector;
