apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
