apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.minio.image }}
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          ports:
            - containerPort: 9000  # API 포트
            - containerPort: 9001  # 웹 콘솔 포트
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: minio-access-key
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: minio-secret-key
          volumeMounts:
            - name: minio-data
              mountPath: /data
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 10
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
