spring:
  application:
    name: report-service
  profiles:
    active: local
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: report-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.xorwns56.report.kafka"

# SpringDoc Swagger UI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus  # prometheus 엔드포인트 노출
  endpoint:
    prometheus:
      enabled: true  # /actuator/prometheus 활성화
