apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petradar.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgres.password | b64enc | quote }}
  spring-datasource-password: {{ .Values.postgres.password | b64enc | quote }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  minio-access-key: {{ .Values.minio.accessKey | b64enc | quote }}
  minio-secret-key: {{ .Values.minio.secretKey | b64enc | quote }}
