export const missingPet = [
  {
    petId: 1,
    petName: "코쇼",
    petType: "고양이",
    petGender: "♀",
    petBreed: "삼색",
    petAge: 2014,
    petMissingDate: "2025-06-17",
    // petColor: "노란색,검은색 얼룩무늬",
    petTitle: "고양이 실종됐어요ㅜㅜ",
    petContent: "시흥시 안현동 근방에서 방 창문 뚫고 탈출함",
    missingPoint: "경기도 시흥시 안현동",
    // REFINE_LOTNO_ADDR: "경기도 남양주시 이패동 484번지",
    // REFINE_ROADNM_ADDR: "경기도 남양주시 경강로163번길 32-27",
  },
  {
    petId: 2,
    petName: "폼폼",
    petType: "강아지",
    petGender: "♀",
    petBreed: "폼피츠",
    petAge: 2025,
    petMissingDate: "2025-06-18",
    // petColor: "흰색",
    petTitle: "산책 중 아이 놓쳤어요!!!겁많아서 제보만 부탁드려요!!",
    petContent: "겁 많은 아이, 산책중 목줄이 풀려서 실종됐습니다.",
    missingPoint: "경기도 시흥시 안현동",
    // REFINE_LOTNO_ADDR: "경기도 안성시 봉남동 326-2번지",
    // REFINE_ROADNM_ADDR: "경기도 안성시 중앙로 431-1",
  },
  {
    petId: 3,
    petName: "비숑",
    petType: "강아지",
    petGender: "♂",
    petBreed: "비숑 프리제",
    petAge: 2024,
    petMissingDate: "2025-06-19",
    // petColor: "흰색",
    petTitle: "흰색 미용된 강아지 보신분",
    petContent: "최근 미용했어요 애교 많습니다. 정왕동 근방에서 실종됐어요",
    missingPoint: "경기도 시흥시 정왕동",
    // "REFINE_LOTNO_ADDR": "경기도 시흥시 정왕동 산15-7번지",
    // "REFINE_ROADNM_ADDR": "경기도 시흥시 뒷방울길 218",
  },
];
