server:
  port: 8083

spring:
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092

# 로그 파일 출력 설정
logging:
  file:
    path: ./logs
    name: ./logs/search-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3
