server:
  port: 8083

spring:
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092

# 로그 파일 출력 설정 (Promtail이 수집)
logging:
  file:
    path: ./logs
    name: ./logs/search-service.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 3

management:
  tracing:
    sampling:
      probability: 1.0  # 로컬에서는 모든 요청 추적
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
